### ISSUE TITLE
bash: npm: command not found

### ISSUE THREAD

**Issue by lifeonmobile** [attm2x/m2x-nodejs#15]
I've installed node.js and all other steps seemed to work but wen I get to the end and type "npm install m2x, I get bash:  npm: command not found.  Thoughts?

Command Line on a Raspberry Pi

**Comment by Jbossalini** [comment]
Sounds like the path may not be complete and it can't find your npm install?   http://oskarhane.com/raspberry-pi-install-node-js-and-npm/

Can you try: `npm -v`

**Comment by fsaravia** [comment]
Closing this one as a stale ticker, @lifeonmobile feel free to reopen or open a new ticket if you have further questions!
