### ISSUE TITLE
Feature request: Collections module

### ISSUE THREAD

**Issue by skazska** [attm2x/m2x-nodejs#16]
Module for collection management is needed

**Comment by fsaravia** [comment]
Hey @skazska, thanks for the issue, we have it in our roadmaps and are planning to add it soon to all our libraries, keep an eye on our releases :).

If you have time or want to also feel free to open a pull request with it, always appreciated!

**Comment by skazska** [comment]
actually i need it right now and forked repo to add it by my self, can i pull it then?

**Comment by fsaravia** [comment]
Yes please, open a PR and we'll take a look to it, thank you!
