### ISSUE TITLE
Distributions: Allow to pass additional parameters when creating a device

### ISSUE THREAD

**Issue by fsaravia** [attm2x/m2x-nodejs#32]
The current version of `Distributions.addDevice` only accepts the serial number as a parameter. Ideally this method should support additional parameters in order to specify name and other properties that devices can take when being created from a distribution.

**Comment by fsaravia** [comment]
[Requested on the M2X Forum](http://developerboards.att.lithium.com/t5/M2X-Data-Service/Distributions-addDevice-problem/m-p/41198)

**Comment by attsdk** [comment]
Implemented in PR #42
