### ISSUE TITLE
lib/response.js -- String.prototype.startsWith undefined

### ISSUE THREAD

**Issue by jbblairiii** [attm2x/m2x-nodejs#34]
String.prototype.startsWith is undefined for NodeJS 4.4.3 on Windows. Which version of NodeJS defines String.prototype.startsWith or is there a need to monkey-patch?

**Comment by jbblairiii** [comment]
Looks like it's specific to collections.deleteCollection. The response from M2X is 204 - No content, yet response.js always looks for 'content-type' in the response.

**Comment by stream7** [comment]
@jbblairiii thank you for reporting this. This should be fixed in version 4.0.1. Could you please try again and close this issue if it is working OK?

**Comment by jbblairiii** [comment]
Working great. Thanks
