### ISSUE TITLE
Add support for Add/Remove Device to/from Collection Endpoints

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-nodejs#36]
Add support for the following endpoints that were added to the [Collections API](https://m2x.att.com/developer/documentation/v2/collections):
* [Add Device to Collection](https://m2x.att.com/developer/documentation/v2/collections#Add-device-to-collection)
* [Remove Device from Collection](https://m2x.att.com/developer/documentation/v2/collections#Remove-device-from-collection)

**Comment by fsaravia** [comment]
Completed in #37
