### ISSUE TITLE
Add List/Iterate Devices Example

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-nodejs#40]
Add a single example file to the [examples](https://github.com/attm2x/m2x-nodejs/tree/master/examples) directory that covers the following:

Iterate Over List of Devices: this example should List Devices and then show how to iterate over the paginated list of devices that is returned by the API. 

Here's a similar example in Python: 
https://github.com/attm2x/m2x-python/blob/master/examples/iterate_over_devices.py

Example should adhere to usage instructions found here: https://github.com/attm2x/m2x-nodejs#example-usage

**Comment by attsdk** [comment]
Implemented in PR #43
