### ISSUE TITLE
Add Export Values Example

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-nodejs#41]
Add a single example file to the [examples](https://github.com/attm2x/m2x-nodejs/tree/master/examples) directory that covers the following:

Export Values from All Data Streams of a Device: this example should first make a call to [Export All Values](https://m2x.att.com/developer/documentation/v2/device#Export-Values-from-all-Data-Streams-of-a-Device) then it should call the [View Job Results](https://m2x.att.com/developer/documentation/v2/jobs#View-Job-Results) endpoint until the export job is completed. Then when the Job is complete the example should get the `result.url` which is the URL where the CSV export can be downloaded.

Here's a similar example in Ruby: 
https://github.com/attm2x/m2x-ruby/blob/master/examples/export_values.rb

Example should adhere to usage instructions found here: 
https://github.com/attm2x/m2x-nodejs#example-usage

**Comment by attsdk** [comment]
Implemented in PR #44
