### ISSUE TITLE
Bug: Output is not accurate in iterate_over_devices.js example

### ISSUE THREAD

**Issue by sankarsubramanian** [attm2x/m2x-nodejs#45]
Example:
$ node examples/iterate_over_devices.js // 3 devices in total,  100 devices per page - correct

Total Number of Devices:  3
Page 1 , Device  1  ::  device description
Page 1 , Device  2  ::  Sample device
Page 1 , Device  3  ::  a
3 'Devices returned on page' 1

$ node examples/iterate_over_devices.js // 3 devices in total, 1 device per page - wrong

Total Number of Devices:  3
3 'Devices returned on page' 3
3 'Devices returned on page' 3
Page 3 , Device  1  ::  device description
Page 3 , Device  2  ::  Sample device
Page 3 , Device  3  ::  a
3 'Devices returned on page' 3

**Comment by kristinpeterson** [comment]
@sankarsubramanian thank you! Is this something you're looking into?

**Comment by majidabdul** [comment]
@sankarsubramanian

**Comment by majidabdul** [comment]
@kristinpeterson : This has been fixed with https://github.com/attm2x/m2x-nodejs/pull/46
