### ISSUE TITLE
uptime example doesnt work without some setup

### ISSUE THREAD

**Issue by monteslu** [attm2x/m2x-nodejs#6]
as is, you'll get http 422 errors with a  body of:
```javascript
{"message":"Validation Failed","errors":{"load_1m":["Stream not found"],"load_5m":["Stream not found"],"load_15m":["Stream not found"]}}
```

Perhaps include a readme of what needs to be setup on the m2x site, or an api call to create the streams?

**Comment by fsaravia** [comment]
@monteslu you need to create the `load_1m`, `load_5m` and `load_15m` streams within your devices. We are going to update the example so it performs that step before actually pushing data, but if you create them manually you will be good to go

**Comment by fsaravia** [comment]
@monteslu Actually, there was an error in the section of the example in charge of creating the test streams, I fixed it now and you should be able to run it.
Thanks for the report!
